add examples/point
getditto/safer_ffi pull request #116
Opened 2022-06-01 16:39 UTC by mw66

Hi,

I just add the example code from README.md to examples/point (and fixed build flag -lm).

Thanks.

2022-06-08 12:51 UTC, danielhenrymantilla requested changes
Thanks for PR! The idea looks very sensible to me; if you can address the nits I've pointed out I'll gladly get it merged 🙂

2022-06-08 12:51 UTC, danielhenrymantilla commented on README.md
> +Please try:
```suggestion
You may try working with the `examples/point` example embedded in the repo:
```

2022-06-08 12:51 UTC, danielhenrymantilla commented on examples/point/Makefile
> +	cc main.c -o main -L ../../target/debug -l point -l pthread -l dl -lm
```suggestion
main: main.c rustlib rust_points.h
	cc $< -o $@ -L ../../target/debug -l point -l pthread -l dl -lm
	
.PHONY: rustlib
rustlib:
	cargo build # --release

rust_points.h:
	cargo test --features c-headers -- generate_headers
```

2022-06-08 12:51 UTC, danielhenrymantilla commented on README.md
> +$ cd examples/point
````suggestion
```bash
git clone https://github.com/getditto/safer_ffi && cd safer_ffi
cd examples/point
````

2022-06-11 04:35 UTC, mw66 commented
Thanks, change committed.

2022-06-27 12:08 UTC, danielhenrymantilla approved these changes

2022-06-27 12:21 UTC, merged